config/routes.rb
EntryApplication::Application.routes.draw do
  devise_for :divers, skip: [:registrations], controllers: {
    omniauth_callbacks: "divers/omniauth_callbacks",
  }
  devise_scope :diver do
    get "signin",                       to: "devise/sessions#new"
    get "signout",                      to: "devise/sessions#destroy"
    get "cancel_diver_registration",    to: "devise/registrations#cancel"
    put "diver_registration",           to: "devise/registrations#update"
    get "edit_diver_registration",      to: "devise/registrations#edit"
  end

  # For testing unhandled exceptions via solid_errors
  get "/crash", to: ->(env) { raise "/crash intentionally generated this error for testing error reporting" }

  # Admin only routes
  authenticate :diver, ->(diver) { diver.admin? } do
    mount SolidErrors::Engine, at: "/errors"

    resources :cleanups, only: [:new, :create]
  end

  resources :agencies, except: [:show]

  resources :animals, except: [:show]

  resources :benthic_covers do
    post :draft, on: :collection
  end

  resources :boat_logs do
    post :draft, on: :collection
  end

  resources :coral_demographics do
    post :draft, on: :collection
  end

  resources :corals, except: [:show]

  resources :cover_cats, except: [:show]

  get "dashboard/show"

  resources :divers, except: [:show]

  resources :habitat_types, except: [:show]

  resources :missions, except: [:show]

  resources :projects, except: [:show]

  resources :regions, except: [:show]

  resources :sample_types, except: [:show]

  resources :samples do
    post :draft, on: :collection
  end

  root to: "home#index"
end

app/models/boat_log.rb
class BoatLog < ApplicationRecord
  has_many :station_logs, dependent: :destroy
  has_many :rep_logs, through: :station_logs
  has_many :divers, through: :rep_logs
  accepts_nested_attributes_for :station_logs, allow_destroy: true

  belongs_to :mission
  has_one :region, through: :mission
  has_one :agency, through: :mission
  has_one :project, through: :mission

  validates :mission_id,          presence: true
  validates :primary_sample_unit, presence: true, length: { is: 4 }
  validates :date,                presence: true

  def boatlog_divers
    boatlog_divers_list = []
    rep_logs.includes([:diver]).each do |rep|
      boatlog_divers_list << [date, rep.field_id, rep.diver.diver_name]
    end
    boatlog_divers_list.sort_by { |e| e[0] }
  end
end

app/models/habitat_type.rb
class HabitatType < ApplicationRecord
  # TODO: Remove after transition to regions relation
  VALID_REGIONS = [
    "Atlantic",
    "Caribbean",
    "FlowerGardens",
  ]

  has_many :samples, dependent: :restrict_with_error
  has_many :benthic_covers, dependent: :restrict_with_error

  has_many :region_habitat_types
  has_many :regions, through: :region_habitat_types

  scope       :atlantic_habitats,           lambda { where(region: "Atlantic") }
  scope       :caribbean_habitats,          lambda { where(region: "Caribbean") }
  scope       :flowergardens_habitats,      lambda { where(region: "FlowerGardens") }

  validates :habitat_name, presence: true
  validates :habitat_description, presence: true
  validates :region, presence: true, inclusion: VALID_REGIONS
end

app/controllers/boat_logs_controller.rb
class BoatLogsController < ApplicationController
  before_action :authenticate_diver!
  load_and_authorize_resource

  # GET /boat_logs
  def index
    @boat_logs = @boat_logs.joins(:mission).includes(:station_logs, :region, :agency, :project)

    # Apply filters
    @filters = {
      "mission.region_id": Array(params[:region_ids]).map(&:to_i),
      "mission.agency_id": Array(params[:agency_ids]).map(&:to_i),
      "mission.project_id": Array(params[:project_ids]).map(&:to_i),
    }.reject { |_, v| v.empty? }
    @unfiltered_boat_logs = @boat_logs
    @boat_logs = @boat_logs.where(@filters)

    respond_to do |format|
      format.html # index.html.erb
      format.xlsx do
        @boat_logs = @boat_logs.includes(station_logs: { rep_logs: :diver })

        # Prevent caching
        no_store
      end
    end
  end

  # GET /boat_logs/1
  def show
  end

  # GET /boat_logs/new
  def new
    @draft = Draft.latest_for(diver_id: current_diver.id, model_klass: BoatLog, model_id: nil)
    if @draft
      @boat_log = @draft.assign_attributes_to(BoatLog.new)
    else
      @boat_log = BoatLog.new.tap do |bl|
        station = bl.station_logs.build
        2.times { station.rep_logs.build }
      end
    end
  end

  # GET /boat_logs/1/edit
  def edit
    @draft = Draft.latest_for(diver_id: current_diver.id, model_klass: BoatLog, model_id: params[:id])
    if @draft
      @draft.assign_attributes_to(@boat_log)
    end
  end

  # POST /boat_logs
  def create
    if @boat_log.save
      Draft.destroy_for(diver_id: current_diver.id, model_klass: BoatLog, model_id: nil)
      redirect_to @boat_log, notice: "Boat log was successfully created."
    else
      render action: "new"
    end
  end

  # PUT /boat_logs/1
  def update
    if @boat_log.update(boat_log_params)
      Draft.destroy_for(diver_id: current_diver.id, model_klass: BoatLog, model_id: @boat_log.id)
      redirect_to @boat_log, notice: "Boat log was successfully updated."
    else
      render action: "edit"
    end
  end

  # DELETE /boat_logs/1
  def destroy
    if @boat_log.destroy
      Draft.destroy_for(diver_id: current_diver.id, model_klass: BoatLog, model_id: @boat_log.id)
      redirect_to boat_logs_url, notice: "Boat log was successfully deleted."
    else
      redirect_to boat_logs_url, alert: "Boat log was not deleted: #{@boat_log.errors.full_messages.join(", ")}"
    end
  end

  # PUT /draft
  def draft
    # Handle intentional delete of draft data
    unless params[:boat_log].present?
      Draft.destroy_for(diver_id: current_diver.id, model_klass: BoatLog, model_id: params[:id])

      head :ok
      return
    end

    draft = Draft.new(
      diver_id: current_diver.id,
      model_klass: BoatLog,
      model_id: params[:id],
      model_attributes: boat_log_params,
      sequence: params[:sequence],
      focused_dom_id: params[:focused_dom_id],
    )
    if draft.save
      render json: {}, status: :created
    else
      render json: draft.errors, status: :unprocessable_entity
    end
  end

  private

  def boat_log_params
    # TODO: Allowing all keys is intentional to reduce risk of a Rails upgrade.
    # Prior to Rails 7, the application used `attr_protected []` at the model
    # level. Mass attribute protection will be introduced gradually separate
    # from the Rails upgrade itself.
    params.require(:boat_log).permit!
  end
end

app/helpers/boat_logs_helper.rb
module BoatLogsHelper
end

app/views/boat_logs/_form.html.erb
<%= nested_form_for @boat_log, data: { "drafts-url": draft_boat_logs_path(id: @boat_log.id), "draft-restored": @draft.present?, "draft-focused-dom-id": @draft&.focused_dom_id }, html: { class: "boat-log-form usa-form maxw-full bg-base-lightest" } do |f| %>
  <%= render "shared/uswds_error_messages", target: @boat_log %>

  <div class="grid-row padding-1">
    <div class="grid-col-12">
      <div>
        <%= label_tag :boat_log_region_id, "Region", class: "usa-label display-inline-block width-card" %>
        <%= select_tag :boat_log_region_id, options_for_select(region_options(current_mission: f.object.mission), f.object.mission.try(:region_id)), include_blank: true, autofocus: true, class: "region-select usa-select usa-input--lg display-inline-block", required: true %>
      </div>

      <div>
        <%= f.label :mission_id, "Mission", class: "usa-label display-inline-block width-card" %>
        <%= f.select :mission_id, mission_options(current_mission: f.object.mission), { include_blank: true }, class: "mission-select usa-select usa-input--lg display-inline-block", required: true %>
      </div>

      <div class="date">
        <%= f.label :date, "Sample Date", class: "usa-label display-inline-block width-card" %>
        <%= f.text_field :date, class: "usa-input usa-input--md display-inline-block" %>
      </div>

      <div>
        <%= f.label :primary_sample_unit, "PSU", class: "usa-label display-inline-block width-card" %>
        <%= f.text_field :primary_sample_unit, class: "usa-input usa-input--sm display-inline-block" %>
      </div>

      <%= f.fields_for :station_logs do |ff| %>
        <div class="grid-container margin-top-1 padding-1 padding-top-0 border">
          <div class="grid-row">
            <div class="grid-col-4">
              <%= ff.label :stn_number, "Station", class: "usa-label display-inline-block width-15" %>
              <%= ff.text_field :stn_number, class: "usa-input usa-input--xs display-inline-block" %>
            </div>
            <div class="grid-col-4">
              <%= ff.label :time, class: "usa-label display-inline-block width-15" %>
              <%= ff.text_field :time, value: ff.object&.time&.strftime("%H:%M"), class: "boatlog_time usa-input usa-input--sm display-inline-block" %>
            </div>
          </div>

          <div class="grid-row">
            <div class="grid-col-4">
              <%= ff.label :latitude_in_northern_degrees, "Latitude (°N)", class: "usa-label display-inline-block width-15" %>
              <%= ff.text_field :latitude_in_northern_degrees, inputmode: "numeric", pattern: "\\d*(\\.\\d*)?", class: "coords coords-positive usa-input usa-input--md display-inline-block" %>
            </div>
            <div class="grid-col-4">
              <%= ff.label :longitude_in_western_degrees, "Longitude (°W)", class: "usa-label display-inline-block width-15" %>
              <%= ff.text_field :longitude_in_western_degrees, inputmode: "numeric", pattern: "\\d*(\\.\\d*)?", class: "coords coords-positive usa-input usa-input--md display-inline-block" %>
            </div>
          </div>

          <%= ff.fields_for :rep_logs do |ff| %>
            <div class="grid-row replicate_record">
              <div class="grid-col-4 replicate_type">
                <%= ff.label :replicate, class: "usa-label display-inline-block width-15" %>
                <%= ff.text_field :replicate, class: "usa-input usa-input--xs display-inline-block" %>
              </div>
              <div class="grid-col-5">
                <%= ff.label :diver_id, "Diver", class: "usa-label display-inline-block width-15 diver_type_label" %>
                <%= ff.collection_select :diver_id, Diver.active_divers.order(:diver_name), :id, :diver_name, { include_blank: true }, class: "usa-select usa-input--lg display-inline-block" %>
              </div>
              <div class="grid-col-3 padding-top-3">
                <%= ff.link_to_remove tabindex: "-1", class: "remove-replicate-link font-body-xs" do %>
                  <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
                    <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#remove_circle") %>
                  </svg>
                  Remove Replicate
                <%- end %>
              </div>
            </div>
          <%- end %>
          <%= ff.link_to_add :rep_logs, class: "add-rep-log-link font-body-xs" do %>
            <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
              <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#add_circle") %>
            </svg>
            Add Replicate
          <%- end %>

          <div class="grid-row">
            <div class="grid-col-12">
              <%= ff.label :comments, "Comments", class: "usa-label display-inline-block width-15 text-top" %>
              <%= ff.text_area :comments, size: "60x3", autocomplete: "off", class: "usa-input usa-input--lg height-10 display-inline-block" %>
            </div>
          </div>

          <div class="grid-row">
            <div class="grid-col-12">
              <%= ff.link_to_remove tabindex: "-1", class: "remove-station-link font-body-xs" do %>
                <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
                  <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#remove_circle") %>
                </svg>
                Remove Station
              <%- end %>
            </div>
          </div>
        </div>
      <%- end %>

      <div>
        <%= f.link_to_add :station_logs, class: "add-station-link font-body-xs" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#add_circle") %>
          </svg>
          Add Station
        <%- end %>
      </div>

      <div>
        <%= f.submit class: "usa-button" %>
      </div>
    </div>
  </div>
<% end %>

app/views/boat_logs/edit.html.erb
<div class="grid-row">
  <div class="grid-col-fill">
    <%= render "shared/nav_breadcrumbs", object: [["Boat Logs", boat_logs_path], ["Edit Boat Log #{@boat_log.primary_sample_unit}", ""]] %>
  </div>
  <div class="grid-col-auto">
    <%= render "draft_progress_uswds", object: @boat_log %> 
  </div>
</div>

<%= render partial: "draft_present_alert", locals: { discard_draft_url: draft_boat_logs_path(id: @boat_log.id) } %>
<%= render "form" %>

app/views/boat_logs/index.html.erb
<%= render "shared/nav_breadcrumbs", object: [["Boat Logs", ""]] %>

<div class="grid-row">
  <div class="grid-col-12 border border-dashed padding-1">
    <%= form_tag boat_logs_path, class: "usa-form maxw-full", method: "get" do %>
      <div>
        <span class="usa-legend width-full usa-input--xl text-bold margin-top-0 margin-right-neg-1 display-inline-block">Regions</span>
        <span class="usa-legend width-full usa-input--xl text-bold margin-top-0 margin-right-neg-1 display-inline-block">Agencies</span>
        <span class="usa-legend width-full usa-input--xl text-bold margin-top-0 margin-right-neg-1 display-inline-block">Projects</span>
      </div>

      <div>
        <%= select_tag :region_ids, options_from_collection_for_select(@unfiltered_boat_logs.map(&:region).uniq.sort_by(&:name), :id, :name, Array(@filters[:"mission.region_id"]) + @boat_logs.distinct.pluck(:"mission.region_id")), class: "usa-input--xl width-full display-inline-block", multiple: true %>
        <%= select_tag :agency_ids, options_from_collection_for_select(@unfiltered_boat_logs.map(&:agency).uniq.sort_by(&:name), :id, :name, Array(@filters[:"mission.agency_id"]) + @boat_logs.distinct.pluck(:"mission.agency_id")), class: "usa-input--xl width-full display-inline-block", multiple: true %>
        <%= select_tag :project_ids, options_from_collection_for_select(@unfiltered_boat_logs.map(&:project).uniq.sort_by(&:name), :id, :name, Array(@filters[:"mission.project_id"]) + @boat_logs.distinct.pluck(:"mission.project_id")), class: "usa-input--xl width-full display-inline-block", multiple: true %>
      </div>

      <div>
        <%= submit_tag "Update Filters", class: "usa-button margin-top-1 display-inline-block" %>
        <%= link_to "Reset Filters", request.path, class: "usa-button usa-button--outline margin-top-1 display-inline-block" %>
      </div>
    <%- end %>
  </div>
</div>

<div class="grid-row">
  <div class="grid-col-12">
    <ul class="usa-button-group margin-bottom-1">
      <li class="usa-button-group__item">
        <%= link_to new_boat_log_path, class: "new-boat-log-button usa-button" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#add") %>
          </svg>
          New Boat Log
        <%- end %>
      </li>
      <li class="usa-button-group__item">
        <%= link_to boat_logs_path(format: "xlsx", region_ids: params[:region_ids], agency_ids: params[:agency_ids], project_ids: params[:project_ids], nocache: SecureRandom.alphanumeric), class: "usa-button usa-button--accent-cool" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#file_download") %>
          </svg> 
          Download Boat Logs (.xlsx)
        <%- end %>
      </li>
    </ul>

    <table class="width-full display">
      <thead>
        <tr>
          <th scope="col" class="width-15">Primary Sample Unit</th>
          <th scope="col" class="width-15">Date</th>
          <th scope="col" class="width-15">Time</th>
          <th scope="col" class="width-auto">Comments</th>
          <th scope="col" class="width-card-lg not-orderable not-searchable"></th>
        </tr>
      </thead>
      <tbody>
        <%- @boat_logs.each do |boat_log| %>
          <tr>
            <td class="width-15"><%= boat_log.primary_sample_unit %></td>
            <td class="width-15 fieldid_check"><%= boat_log.date %></td>
            <td class="width-15"><%= boat_log.station_logs&.first&.time&.strftime("%H:%M") %></td>
            <td class="width-auto"><%= boat_log.station_logs&.first&.comments %></td>
            <td class="width-card-lg">
              <ul class="usa-button-group float-right">
                <li class="usa-button-group__item">
                  <%= link_to "View", boat_log, class: "usa-button" %>
                </li>
                <li class="usa-button-group__item">
                  <%= link_to "Edit", edit_boat_log_path(boat_log), class: "usa-button usa-button--outline" %>
                </li>
              </ul>
            </td>
          </tr>
        <%- end %>
      </tbody>
    </table>
  </div>
</div>

app/views/boat_logs/new.html.erb
<div class="grid-row">
  <div class="grid-col-fill">
    <%= render "shared/nav_breadcrumbs", object: [["Boat Logs", boat_logs_path], ["New Boat Log", ""]] %>
  </div>
  <div class="grid-col-auto">
    <%= render "draft_progress_uswds", object: @boat_log %> 
  </div>
</div>

<%= render partial: "draft_present_alert", locals: { discard_draft_url: draft_boat_logs_path(id: @boat_log.id) } %>
<%= render "form" %>

app/views/boat_logs/show.html.erb
<div class="grid-row">
  <div class="grid-col-12">
    <%= render "shared/nav_breadcrumbs", object: [["Boat Logs", boat_logs_path], ["Boat Log #{@boat_log.primary_sample_unit}", ""]] %>
  </div>
</div>

<div class="grid-row maxw-full bg-base-lightest">
  <div class="grid-col-6 padding-1">
    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Mission</span>
      <span class="width-mobile display-inline-block"><%= @boat_log.mission&.display_name(include_region: true) %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Sample Date</span>
      <span class="width-mobile display-inline-block"><%= @boat_log.date %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">PSU</span>
      <span class="width-mobile display-inline-block"><%= @boat_log.primary_sample_unit %></span>
    </div>
  </div>
  <div class="grid-col-6 padding-1">
    <div class="margin-1">
      <table class="usa-table maxw-full margin-top-0">
        <thead>
          <tr>
            <th scope="col">Diver</th>
            <th scope="col">Field ID</th>
          </tr>
        </thead>
        <tbody>
          <%- @boat_log.rep_logs.includes(:station_log, :diver).each do |rep_log| %>
            <tr>
              <td class="text-bold"><%= rep_log.diver&.diver_name %></td>
              <td><%= rep_log.field_id %></td>
            </tr>
          <%- end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="grid-row maxw-full bg-base-lightest">
  <div class="grid-col-12 padding-1">
    <ul class="usa-button-group">
      <li class="usa-button-group__item">
        <%= link_to boat_logs_path, class: "usa-button" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#arrow_back") %>
          </svg>
          Back to List
        <%- end %>
      </li>
      <li class="usa-button-group__item">
        <%= link_to "Edit", edit_boat_log_path(@boat_log), class: "usa-button usa-button--outline" %>
      </li>
      <li class="usa-button-group__item">
        <%= link_to "Delete", @boat_log, data: { confirm: "Are you sure?" }, method: "delete", class: "usa-button usa-button--secondary" %>
      </li>
    </ul>
  </div>
</div>