config/routes.rb
EntryApplication::Application.routes.draw do
  devise_for :divers, skip: [:registrations], controllers: {
    omniauth_callbacks: "divers/omniauth_callbacks",
  }
  devise_scope :diver do
    get "signin",                       to: "devise/sessions#new"
    get "signout",                      to: "devise/sessions#destroy"
    get "cancel_diver_registration",    to: "devise/registrations#cancel"
    put "diver_registration",           to: "devise/registrations#update"
    get "edit_diver_registration",      to: "devise/registrations#edit"
  end

  # For testing unhandled exceptions via solid_errors
  get "/crash", to: ->(env) { raise "/crash intentionally generated this error for testing error reporting" }

  # Admin only routes
  authenticate :diver, ->(diver) { diver.admin? } do
    mount SolidErrors::Engine, at: "/errors"

    resources :cleanups, only: [:new, :create]
  end

  resources :agencies, except: [:show]

  resources :animals, except: [:show]

  resources :benthic_covers do
    post :draft, on: :collection
  end

  resources :boat_logs do
    post :draft, on: :collection
  end

  resources :coral_demographics do
    post :draft, on: :collection
  end

  resources :corals, except: [:show]

  resources :cover_cats, except: [:show]

  get "dashboard/show"

  resources :divers, except: [:show]

  resources :habitat_types, except: [:show]

  resources :missions, except: [:show]

  resources :projects, except: [:show]

  resources :regions, except: [:show]

  resources :sample_types, except: [:show]

  resources :samples do
    post :draft, on: :collection
  end

  root to: "home#index"
end

app/models/habitat_type.rb
class HabitatType < ApplicationRecord
  # TODO: Remove after transition to regions relation
  VALID_REGIONS = [
    "Atlantic",
    "Caribbean",
    "FlowerGardens",
  ]

  has_many :samples, dependent: :restrict_with_error
  has_many :benthic_covers, dependent: :restrict_with_error

  has_many :region_habitat_types
  has_many :regions, through: :region_habitat_types

  scope       :atlantic_habitats,           lambda { where(region: "Atlantic") }
  scope       :caribbean_habitats,          lambda { where(region: "Caribbean") }
  scope       :flowergardens_habitats,      lambda { where(region: "FlowerGardens") }

  validates :habitat_name, presence: true
  validates :habitat_description, presence: true
  validates :region, presence: true, inclusion: VALID_REGIONS
end

app/models/sample.rb
class Sample < ApplicationRecord
  include CommonFields

  belongs_to :diver
  belongs_to :buddy, class_name: "Diver"

  belongs_to :sample_type
  belongs_to :habitat_type

  belongs_to :mission
  has_one :region, through: :mission
  has_one :agency, through: :mission
  has_one :project, through: :mission

  has_many :sample_animals, dependent: :destroy
  validates_presence_of :sample_animals, message: "you must have at leat one species record (can be NO FISH)"
  has_many :animals, through: :sample_animals
  accepts_nested_attributes_for :sample_animals, reject_if: lambda {  |a| a[:animal_id].blank? }, allow_destroy: true

  validates :mission_id,                  presence: true
  # validates :sample_date,                 :presence => true
  validates :sample_type_id,              presence: true
  validates :habitat_type_id,             presence: true

  validates :dive_begin_time,             presence: true
  validates :dive_end_time,               presence: true
  validate  :dive_starts_before_ends
  validates :sample_begin_time,           presence: true
  validate  :sample_starts_after_dive_and_before_end
  validates :sample_end_time,             presence: true
  validate  :sample_ends_before_dive_ends
  validate  :sample_starts_before_ends

  validates :field_id,                    presence: true
  validates_format_of :field_id,          with: /\A\d{5}[a-zA-Z]\z/
  validates :dive_depth,                  presence: true, numericality: true
  validates :sample_depth,                presence: true, numericality: true
  validates :underwater_visibility,       presence: true, numericality: true
  validates :water_temp,                  presence: true, numericality: true
  validates :sample_description,          length: { maximum: 150 }

  validates :substrate_max_depth,         presence: true, numericality: { only_integer: true }
  validates :substrate_min_depth,         presence: true, numericality: { only_integer: true, less_than_or_equal_to: :substrate_max_depth }

  validates :hard_verticle_relief,         presence: true, numericality: true
  validates :soft_verticle_relief,         presence: true, numericality: true

  validates :hard_relief_cat_0,           presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :hard_relief_cat_1,           presence: true, if: -> { hard_verticle_relief > 0.2 }, numericality: { only_integer: true, greater_than: 0 }
  validates :hard_relief_cat_2,           presence: true, if: -> { hard_verticle_relief > 0.5 }, numericality: { only_integer: true, greater_than: 0 }
  validates :hard_relief_cat_3,           presence: true, if: -> { hard_verticle_relief > 1.0 }, numericality: { only_integer: true, greater_than: 0 }
  validates :hard_relief_cat_4,           presence: true, if: -> { hard_verticle_relief > 1.5 }, numericality: { only_integer: true, greater_than: 0 }

  validate :hard_relief_cats_equal_100
  validate :soft_relief_cats_equal_100
  validate :abiotic_percentage_equal_100
  validate :biotic_percentage_sand_equal_100, if: :sand_percentage?
  validate :biotic_percentage_hardbottom_equal_100, if: :hardbottom_percentage?


  def msn_prefix
    "A"
  end

   private


  def sample_starts_before_ends
    if self.sample_begin_time >= self.sample_end_time
      self.errors.add :sample_end_time, " has to end after begin time "
    end
  end

  def dive_starts_before_ends
    if self.dive_begin_time >= self.dive_end_time
      self.errors.add :dive_end_time, " has to end after begin time "
    end
  end

  def sample_starts_after_dive_and_before_end
    if self.sample_begin_time <= self.dive_begin_time || self.sample_begin_time > self.dive_end_time
      self.errors.add :sample_begin_time, "Sample start time has to be after dive start or before dive end"
    end
  end

  def sample_ends_before_dive_ends
    if self.sample_end_time > self.dive_end_time
      self.errors.add :sample_end_time, "Sample end time has to be before dive end time"
    end
  end

  def hard_relief_cats_equal_100
      values = []
      [self.hard_relief_cat_0, self.hard_relief_cat_1, self.hard_relief_cat_2, self.hard_relief_cat_3, self.hard_relief_cat_4].each do |cat|
        if !cat.nil?
          values.push(cat)
        end
      end
      values.delete_if { |x| x == nil }
      if (values.sum) != 100
        errors.add(:base, "hard relief categories do not add to 100")
      end
  end

  def soft_relief_cats_equal_100
      values = []
      [self.soft_relief_cat_0, self.soft_relief_cat_1, self.soft_relief_cat_2, self.soft_relief_cat_3, self.soft_relief_cat_4].each do |cat|
        if !cat.nil?
          values.push(cat)
        end
      end
      values.delete_if { |x| x == nil }
      if (values.sum) != 100
        errors.add(:base, "soft relief categories do not add to 100")
      end
  end

  def abiotic_percentage_equal_100
      values = []
      [self.sand_percentage, self.hardbottom_percentage, rubble_percentage].each do |cat|
        if !cat.nil?
          values.push(cat)
        end
      end
      values.delete_if { |x| x == nil }
      if (values.sum) != 100
        errors.add(:base, "abiotic percentages do not add to 100")
      end
  end

  def biotic_percentage_sand_equal_100
      values = []
      [self.sand_bare, self.sand_macro_algae, self.sand_seagrass, self.sand_sponge, self.sand_pcov_other1, self.sand_pcov_other2].each do |cat|
        if !cat.nil?
          values.push(cat)
        end
      end
      values.delete_if { |x| x == nil }
      if (values.sum) != 100
        errors.add(:base, "Sand biotic percentages do not add to 100")
      end
  end

  def biotic_percentage_hardbottom_equal_100
      values = []
      [self.hardbottom_algal_turf, self.hardbottom_macro_algae, self.hardbottom_live_coral, self.hardbottom_octocoral, self.hardbottom_sponge, self.hard_pcov_other1, self.hard_pcov_other2].each do |cat|
        if !cat.nil?
          values.push(cat)
        end
      end
      values.delete_if { |x| x == nil }
      if (values.sum) != 100
        errors.add(:base, "Hardbottom biotic percentages do not add to 100")
      end
  end
end

app/models/sample_type.rb
class SampleType < ApplicationRecord
  has_many :samples, dependent: :restrict_with_error

  validates :sample_type_name, presence: true
  validates :sample_type_description, presence: true

  # Returns the default (most likely to be used) sample type, if it exists
  def self.default
    SampleType.where(sample_type_name: "Bohn-Bannerot Point").first
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :authenticate_diver!
  load_and_authorize_resource

  # GET /samples
  def index
    @samples = @samples.joins(:mission).includes(:diver, :region, :agency, :project)

    # Apply filters
    @filters = {
      "mission.region_id": Array(params[:region_ids]).map(&:to_i),
      "mission.agency_id": Array(params[:agency_ids]).map(&:to_i),
      "mission.project_id": Array(params[:project_ids]).map(&:to_i),
    }.reject { |_, v| v.empty? }
    @unfiltered_samples = @samples
    @samples = @samples.where(@filters)

    respond_to do |format|
      format.html
      format.xlsx do
        # Prevent caching
        no_store

        @samples = @samples.includes(:buddy, :habitat_type, sample_animals: :animal)
      end
      format.pdf do
        # Prevent caching
        no_store

        diver = Diver.find(params[:diver_id].presence || current_diver.id)
        @samples = @samples.
          where(diver: diver).
          includes(:buddy, :habitat_type, sample_animals: :animal).
          order(:sample_date, :sample_begin_time)
        pdf = SamplePdf.new(@samples, params[:fishtype].to_s)

        send_data pdf.render, filename: "#{diver.diver_name}_ProofingReport.pdf",
          type: "application/pdf"
      end
    end
  end

  # GET /samples/1
  def show
  end

  # GET /samples/new
  def new
    @draft = Draft.latest_for(diver_id: current_diver.id, model_klass: Sample, model_id: nil)
    if @draft
      @draft.assign_attributes_to(@sample)
    else
      @sample.diver_id = current_diver.id
      @sample.sample_type = SampleType.default
      @sample.sample_animals.build
    end
  end

  # GET /samples/1/edit
  def edit
    @draft = Draft.latest_for(diver_id: current_diver.id, model_klass: Sample, model_id: params[:id])
    if @draft
      @draft.assign_attributes_to(@sample)
    end
  end

  # POST /samples
  def create
    if @sample.save
      Draft.destroy_for(diver_id: current_diver.id, model_klass: Sample, model_id: nil)
      redirect_to samples_url, notice: "Sample was successfully created."
    else
      render action: "new"
    end
  end

  # PUT /samples/1
  def update
    if @sample.update(sample_params)
      Draft.destroy_for(diver_id: current_diver.id, model_klass: Sample, model_id: @sample.id)
      redirect_to samples_url, notice: "Sample was successfully updated."
    else
      render action: "edit"
    end
  end

  # DELETE /samples/1
  def destroy
    if @sample.destroy
      redirect_to samples_url, notice: "Sample was successfully deleted."
    else
      redirect_to samples_url, alert: "Sample was not deleted: #{@sample.errors.full_messages.join(", ")}"
    end
  end

  # PUT /draft
  def draft
    # Handle intentional delete of draft data
    unless params[:sample].present?
      Draft.destroy_for(diver_id: current_diver.id, model_klass: Sample, model_id: params[:id])

      head :ok
      return
    end

    draft = Draft.new(
      diver_id: current_diver.id,
      model_klass: Sample,
      model_id: params[:id],
      model_attributes: sample_params,
      sequence: params[:sequence],
      focused_dom_id: params[:focused_dom_id],
    )
    if draft.save
      render json: {}, status: :created
    else
      render json: draft.errors, status: :unprocessable_entity
    end
  end

  private

  def sample_params
    # TODO: Allowing all keys is intentional to reduce risk of a Rails upgrade.
    # Prior to Rails 7, the application used `attr_protected []` at the model
    # level. Mass attribute protection will be introduced gradually separate
    # from the Rails upgrade itself.
    params.require(:sample).permit!
  end
end

app/views/samples/edit.html.erb
<div class="grid-row">
  <div class="grid-col-fill">
    <%= render "shared/nav_breadcrumbs", object: [["Fish Samples", samples_path], ["Edit Fish Sample #{@sample.field_id}", ""]] %>
  </div>
  <div class="grid-col-auto">
    <%= render "draft_progress_uswds", object: @sample %> 
  </div>
</div>

<%= render partial: "draft_present_alert", locals: { discard_draft_url: draft_samples_path(id: @sample.id) } %>
<%= render "form" %>

app/views/samples/index.html.erb
<%= render "shared/nav_breadcrumbs", object: [["Fish Samples", ""]] %>

<div class="grid-row">
  <div class="grid-col-12 border border-dashed padding-1">
    <%= form_tag samples_path, class: "usa-form maxw-full", method: "get" do %>
      <div>
        <span class="usa-legend width-full usa-input--xl text-bold margin-top-0 margin-right-neg-1 display-inline-block">Regions</span>
        <span class="usa-legend width-full usa-input--xl text-bold margin-top-0 margin-right-neg-1 display-inline-block">Agencies</span>
        <span class="usa-legend width-full usa-input--xl text-bold margin-top-0 margin-right-neg-1 display-inline-block">Projects</span>
      </div>

      <div>
        <%= select_tag :region_ids, options_from_collection_for_select(@unfiltered_samples.map(&:region).uniq.sort_by(&:name), :id, :name, Array(@filters[:"mission.region_id"]) + @samples.distinct.pluck(:"mission.region_id")), class: "usa-input--xl width-full display-inline-block", multiple: true %>
        <%= select_tag :agency_ids, options_from_collection_for_select(@unfiltered_samples.map(&:agency).uniq.sort_by(&:name), :id, :name, Array(@filters[:"mission.agency_id"]) + @samples.distinct.pluck(:"mission.agency_id")), class: "usa-input--xl width-full display-inline-block", multiple: true %>
        <%= select_tag :project_ids, options_from_collection_for_select(@unfiltered_samples.map(&:project).uniq.sort_by(&:name), :id, :name, Array(@filters[:"mission.project_id"]) + @samples.distinct.pluck(:"mission.project_id")), class: "usa-input--xl width-full display-inline-block", multiple: true %>
      </div>

      <div>
        <%= submit_tag "Update Filters", class: "usa-button margin-top-1 display-inline-block" %>
        <%= link_to "Reset Filters", request.path, class: "usa-button usa-button--outline margin-top-1 display-inline-block" %>
      </div>
    <%- end %>
  </div>
</div>

<div class="grid-row">
  <div class="grid-col-12">
    <ul class="usa-button-group margin-top-1">
      <li class="usa-button-group__item">
        <%= link_to new_sample_path, class: "new-sample-button usa-button" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#add") %>
          </svg>
          New Sample
        <%- end %>
      </li>
      <li class="usa-button-group__item">
        <%= link_to samples_path(format: "pdf", region_ids: params[:region_ids], agency_ids: params[:agency_ids], project_ids: params[:project_ids], diver_id: current_diver.id, fishtype: "species_code", nocache: SecureRandom.alphanumeric), class: "usa-button usa-button--accent-cool" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#file_download") %>
          </svg> 
          <div>
            Proofing Report (.pdf)<br><span class="font-body-3xs">(species code)</span>
          </div>
        <%- end %>
      </li>
      <li class="usa-button-group__item">
        <%= link_to samples_path(format: "pdf", region_ids: params[:region_ids], agency_ids: params[:agency_ids], project_ids: params[:project_ids], diver_id: current_diver.id, fishtype: "common_name", nocache: SecureRandom.alphanumeric), class: "usa-button usa-button--accent-cool" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#file_download") %>
          </svg> 
          <div>
            Proofing Report (.pdf)<br><span class="font-body-3xs">(common name)</span>
          </div>
        <%- end %>
      </li>
      <%- if current_diver.admin? || current_diver.missions_managed.any? %>
        <li class="usa-button-group__item">
          <%= link_to samples_path(format: "xlsx", region_ids: params[:region_ids], agency_ids: params[:agency_ids], project_ids: params[:project_ids], nocache: SecureRandom.alphanumeric), class: "usa-button usa-button--accent-cool" do %>
            <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
              <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#file_download") %>
            </svg> 
            Samples (.xlsx)
          <%- end %>
        </li>
        <li class="usa-button-group__item">
          <%= link_to "#diver-proofing-report-modal", class: "usa-button usa-button--accent-warm", "aria-controls": "diver-proofing-report-modal", "data-open-modal": true do %>
            <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
              <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#people") %>
            </svg> 
            Diver Proofing Reports
          <%- end %>
          <div class="usa-modal" id="diver-proofing-report-modal" aria-labelledby="diver-proofing-report-modal-heading" aria-describedby="diver-proofing-report-modal-description">
            <div class="usa-modal__content">
              <div class="usa-modal__main">
                <h2 id="diver-proofing-report-modal-heading" class="usa-modal__heading">
                  <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
                    <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#people") %>
                  </svg> 
                  Diver Proofing Reports
                </h2>
                <div id="diver-proofing-report-modal-description">
                  <%= form_tag samples_path(format: "pdf"), class: "usa-form", method: "get" do %>
                    <%- Array(params[:region_ids]).each do |region_id| %>
                      <%= hidden_field_tag :"region_ids[]", region_id %>
                    <%- end %>
                    <%- Array(params[:agency_ids]).each do |agency_id| %>
                      <%= hidden_field_tag :"agency_ids[]", agency_id %>
                    <%- end %>
                    <%- Array(params[:project_ids]).each do |project_id| %>
                      <%= hidden_field_tag :"project_ids[]", project_id %>
                    <%- end %>
                    <%= hidden_field_tag :fishtype, "common_name" %>
                    <%= hidden_field_tag :nocache, SecureRandom.alphanumeric %>

                    <%= select_tag :diver_id, options_from_collection_for_select(@samples.map(&:diver).uniq.sort_by(&:diver_name), :id, :diver_name), class: "usa-select usa-input--lg" %>

                    <%= button_tag class: "usa-button" do %>
                      <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
                        <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#file_download") %>
                      </svg> 
                      Proofing Report (.pdf)
                    <%- end %>

                    <%= button_tag "Close", type: "button", class: "usa-button usa-button--outline", "data-close-modal": true %>
                  <%- end %>
                </div>
              </div>

              <%= button_tag type: "button", class: "usa-button usa-modal__close", "aria-label": "Close this dialog", "data-close-modal": true do %>
                <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
                  <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#close") %>
                </svg> 
              <%- end %>
            </div>
          </div>
        </li>
      <%- end %>
    </ul>
  </div>
</div>

<div class="grid-row">
  <div class="grid-col-12">
    <table class="width-full display">
      <thead>
        <tr>
          <th scope="col" class="width-card">Diver</th>
          <th scope="col" class="width-15">Field ID</th>
          <th scope="col" class="width-15">Date</th>
          <th scope="col" class="width-15">Sample Start Time</th>
          <th scope="col" class="width-card-lg not-orderable not-searchable"></th>
        </tr>
      </thead>
      <tbody>
        <%- @samples.each do |sample| %>
          <%= tag.tr "data-id": sample.id do %>
            <td class="width-card"><%= sample.diver&.diver_name %></td>
            <td class="width-15 fieldid_check"><%= sample.field_id %></td>
            <td class="width-15"><%= sample.sample_date %></td>
            <td class="width-15"><%= sample.sample_begin_time&.strftime("%H:%M") %></td>
            <td class="width-card-lg">
              <ul class="usa-button-group float-right">
                <li class="usa-button-group__item">
                  <%= link_to "View", sample, class: "view-sample-button usa-button" %>
                </li>
                <li class="usa-button-group__item">
                  <%= link_to "Edit", edit_sample_path(sample), class: "edit-sample-button usa-button usa-button--outline" %>
                </li>
              </ul>
            </td>
          <%- end %>
        <%- end %>
      </tbody>
    </table>
  </div>
</div>

app/views/samples/new.html.erb
<div class="grid-row">
  <div class="grid-col-fill">
    <%= render "shared/nav_breadcrumbs", object: [["Fish Samples", samples_path], ["New Fish Sample", ""]] %>
  </div>
  <div class="grid-col-auto">
    <%= render "draft_progress_uswds", object: @sample %> 
  </div>
</div>

<%= render partial: "draft_present_alert", locals: { discard_draft_url: draft_samples_path(id: @sample.id) } %>
<%= render "form" %>

app/views/samples/show.html.erb
<div class="grid-row">
  <div class="grid-col-12">
    <%= render "shared/nav_breadcrumbs", object: [["Fish Samples", samples_path], ["Fish Sample #{@sample.field_id}", ""]] %>
  </div>
</div>

<div class="grid-row maxw-full bg-base-lightest">
  <div class="grid-col-6 padding-1">
    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Mission</span>
      <span class="width-mobile display-inline-block"><%= @sample.mission&.display_name(include_region: true) %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Sample Date</span>
      <span class="width-mobile display-inline-block"><%= @sample.sample_date %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Diver</span>
      <span class="width-mobile display-inline-block"><%= @sample.diver&.diver_name %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Buddy</span>
      <span class="width-mobile display-inline-block"><%= Diver.find_by(id: @sample.buddy)&.diver_name %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Sample Type</span>
      <span class="width-mobile display-inline-block"><%= @sample.sample_type&.sample_type_name %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Habitat Type</span>
      <span class="width-mobile display-inline-block"><%= @sample.habitat_type&.habitat_name %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Dive Begin Time</span>
      <span class="width-mobile display-inline-block"><%= @sample.dive_begin_time&.strftime("%H:%M") %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Dive End Time</span>
      <span class="width-mobile display-inline-block"><%= @sample.dive_end_time&.strftime("%H:%M") %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Sample Begin Time</span>
      <span class="width-mobile display-inline-block"><%= @sample.sample_begin_time&.strftime("%H:%M") %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Sample End Time</span>
      <span class="width-mobile display-inline-block"><%= @sample.sample_end_time&.strftime("%H:%M") %></span>
    </div>

    <div class="margin-1 margin-top-2">
      <ul class="usa-button-group">
        <li class="usa-button-group__item">
          <%= link_to samples_path, class: "list-button usa-button" do %>
            <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
              <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#arrow_back") %>
            </svg>
            Back to List
          <%- end %>
        </li>
        <li class="usa-button-group__item">
          <%= link_to "Edit", edit_sample_path(@sample), class: "edit-button usa-button usa-button--outline" %>
        </li>
        <li class="usa-button-group__item">
          <%= link_to "Delete", @sample, data: { confirm: "Are you sure?" }, method: "delete", class: "delete-button usa-button usa-button--secondary" %>
        </li>
      </ul>
    </div>
  </div>
  <div class="grid-col-6 padding-1">
    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Field ID</span>
      <span class="width-card-lg display-inline-block"><%= @sample.field_id %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Max Dive Depth</span>
      <span class="width-card-lg display-inline-block"><%= @sample.dive_depth %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Station Depth</span>
      <span class="width-card-lg display-inline-block"><%= @sample.sample_depth %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Visibility</span>
      <span class="width-card-lg display-inline-block"><%= @sample.underwater_visibility %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Water Temp</span>
      <span class="width-card-lg display-inline-block"><%= @sample.water_temp %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Current</span>
      <span class="width-card-lg display-inline-block"><%= @sample.current %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Fishing Gear</span>
      <span class="width-card-lg display-inline-block"><%= @sample.fishing_gear %></span>
    </div>

    <div class="margin-1">
      <span class="width-card margin-right-1 text-bold display-inline-block">Comments</span>
      <span class="width-card-lg display-inline-block"><%= @sample.sample_description %></span>
    </div>
  </div>
</div>