config/routes.rb
EntryApplication::Application.routes.draw do
  devise_for :divers, skip: [:registrations], controllers: {
    omniauth_callbacks: "divers/omniauth_callbacks",
  }
  devise_scope :diver do
    get "signin",                       to: "devise/sessions#new"
    get "signout",                      to: "devise/sessions#destroy"
    get "cancel_diver_registration",    to: "devise/registrations#cancel"
    put "diver_registration",           to: "devise/registrations#update"
    get "edit_diver_registration",      to: "devise/registrations#edit"
  end

  # For testing unhandled exceptions via solid_errors
  get "/crash", to: ->(env) { raise "/crash intentionally generated this error for testing error reporting" }

  # Admin only routes
  authenticate :diver, ->(diver) { diver.admin? } do
    mount SolidErrors::Engine, at: "/errors"

    resources :cleanups, only: [:new, :create]
  end

  resources :agencies, except: [:show]

  resources :animals, except: [:show]

  resources :benthic_covers do
    post :draft, on: :collection
  end

  resources :boat_logs do
    post :draft, on: :collection
  end

  resources :coral_demographics do
    post :draft, on: :collection
  end

  resources :corals, except: [:show]

  resources :cover_cats, except: [:show]

  get "dashboard/show"

  resources :divers, except: [:show]

  resources :habitat_types, except: [:show]

  resources :missions, except: [:show]

  resources :projects, except: [:show]

  resources :regions, except: [:show]

  resources :sample_types, except: [:show]

  resources :samples do
    post :draft, on: :collection
  end

  root to: "home#index"
end

app/models/diver.rb
class Diver < ApplicationRecord
  DIVER   = "diver"
  ADMIN   = "admin"
  ROLES   = [DIVER, ADMIN]

  devise :database_authenticatable, :recoverable, :registerable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:icam, :developer]

  has_many    :samples
  has_many    :samples_missions, through: :samples

  has_many    :benthic_covers
  has_many    :coral_demographics

  has_many    :rep_logs

  has_many :mission_managers
  has_many :missions_managed, through: :mission_managers, source: :mission

  validates   :diver_number, presence: true, uniqueness: true
  validates   :diver_name, presence: true, uniqueness: { case_sensitive: false }
  validates   :agency, presence: true, except_on: [:admin, :import]
  validates   :username, uniqueness: { case_sensitive: false }
  validates   :email, uniqueness: { case_sensitive: false }
  validates   :role, inclusion: { in: ROLES }
  validate    :current_password_is_not_username, except_on: [:admin, :import], unless: -> { password.present? }
  validate    :password_is_not_username, except_on: [:admin, :import], if: -> { password.present? }

  scope       :active_divers,      lambda { where(active: true) }

  # Temporarily allow a diver to be found by "login" which is EITHER email or
  # username.
  #
  # Eventually username will be deprecated.
  def self.find_first_by_auth_conditions(tainted_conditions, opts = {})
    conditions = devise_parameter_filter.filter(tainted_conditions).merge(opts)
    login = conditions.delete(:login)

    relation = where(conditions)
    if login
      relation = relation.where("(email IS NOT NULL AND LENGTH(email) > 0 AND LOWER(email) = LOWER(:login)) OR (username IS NOT NULL AND LENGTH(username) > 0 AND LOWER(username) = LOWER(:login))", login: login)
    end

    relation.first
  end

  def diver?
    self.role == Diver::DIVER
  end

  def admin?
    self.role == Diver::ADMIN
  end

  def active_for_authentication?
    # Do not allow deprecated "boatlog manager" users to login anymore
    super && ROLES.include?(self.role)
  end

  def inactive_message
    if !ROLES.include?(self.role)
      return "Your diver role is not valid."
    end

    super
  end

  # Login always returns email address. However, during a transition period, a
  # diver may use email OR username as their login for authentication.
  #
  # See Diver.find_first_by_auth_conditions for the implementation of login
  # via email or username.
  def login
    email
  end

  def login=(login)
    # login cannot be set directly
  end

  def current_password_is_not_username
    if username.present? && valid_password?(username)
      errors.add(:password, "must not be the same as username")
    end
  end

  def password_is_not_username
    if (username.present? && username.downcase == password.downcase) || diver_name.downcase == password.downcase || email.downcase == password.downcase
      errors.add(:password, "must not be the same as username, diver name or email")
    end
  end
end

app/controllers/divers/omniauth_callbacks_controller.rb
class Divers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-openid-providers
  skip_before_action :verify_authenticity_token, only: [:icam]

  def developer
    # Additional check to make sure this never runs in production
    unless Rails.env.development?
      head :not_found
      return
    end

    user = Diver.find_by!(email: request.env["omniauth.auth"].uid)

    set_flash_message!(:notice, :success, kind: "Developer")
    sign_in_and_redirect user, event: :authentication
  rescue ActiveRecord::RecordNotFound
    set_flash_message!(:alert, :failure, kind: "Developer", reason: "No diver with that email address exists. Please contact the NCRMP team to request an account.")
    redirect_to after_omniauth_failure_path_for(resource_name)
  end

  def icam
    user = Diver.find_by!(email: request.env["omniauth.auth"].info.email)

    set_flash_message!(:notice, :success, kind: "ICAM")
    sign_in_and_redirect user, event: :authentication
  rescue ActiveRecord::RecordNotFound
    set_flash_message!(:alert, :failure, kind: "ICAM", reason: "No diver with that email address exists. Please contact the NCRMP team to request an account.")
    redirect_to after_omniauth_failure_path_for(resource_name)
  end
end

app/controllers/divers_controller.rb
class DiversController < ApplicationController
  before_action :authenticate_diver!
  load_and_authorize_resource

  # GET /divers
  def index
    @divers = @divers.order(:diver_number)

    respond_to do |format|
      format.html # index.html.erb
      format.xlsx do
        # Prevent caching
        no_store
      end
    end
  end

  # GET /divers/new
  def new
  end

  # GET /divers/1/edit
  def edit
  end

  # POST /divers
  def create
    if @diver.save(context: :admin)
      redirect_to divers_url, notice: "Diver was successfully created."
    else
      render action: "new"
    end
  end

  # PUT /divers/1
  def update
    saved = @diver.with_transaction_returning_status do
      @diver.assign_attributes(diver_params)
      @diver.save(context: :admin)
    end

    if saved
      redirect_to divers_url, notice: "Diver was successfully updated."
    else
      render action: "edit"
    end
  end

  # DELETE /divers/1
  def destroy
    if @diver.destroy
      redirect_to divers_url, notice: "Diver was successfully deleted."
    else
      redirect_to divers_url, alert: "Diver was not deleted: #{@diver.errors.full_messages.join(", ")}"
    end
  end

  private

  def diver_params
    allowed_keys = [
      :active, :diver_number, :diver_name, :username, :password, :password_confirmation, :email, :agency, :current_password,
    ]

    allowed_keys << :role if current_diver.admin?

    params.require(:diver).permit(*allowed_keys).tap do |params|
      params.delete(:password) if params[:password].blank?
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
  end
end

app/helpers/divers_helper.rb
module DiversHelper
end

app/views/divers/_form.html.erb
<%= form_for @diver, html: { class: "usa-form maxw-full bg-base-lightest", autocomplete: "off" } do |f| %>
  <%= render "shared/uswds_error_messages", target: @diver %>

  <div class="grid-row padding-1">
    <div class="grid-col-12">
      <%= f.check_box :active, class: "usa-checkbox__input", autocomplete: "off" %>
      <%= f.label :active, "Active?", class: "usa-checkbox__label" %>

      <%= f.label :diver_number, class: "usa-label" %>
      <%= f.text_field :diver_number, class: "usa-input usa-input--md", required: true, autocomplete: "off" %>
      
      <%= f.label :diver_name, class: "usa-label" %>
      <%= f.text_field :diver_name, class: "usa-input usa-input--xl", required: true, autocomplete: "off" %>

      <%= f.label :username, class: "usa-label" %>
      <%= f.text_field :username, class: "usa-input usa-input--xl", required: true, autocomplete: "off" %>

      <%= f.label :email, class: "usa-label" %>
      <%= f.text_field :email, class: "usa-input usa-input--xl", required: true, autocomplete: "off" %>

      <%= f.label :agency, class: "usa-label" %>
      <%= f.text_field :agency, class: "usa-input usa-input--md "%>
      
      <%= f.label :password, "Password (leave blank to leave it unchanged)", class: "usa-label" %>
      <%= f.password_field :password, class: "usa-input usa-input--xl", autocomplete: "new-password" %>

      <%= f.label :password_confirmation, "New password confirmation (leave blank to leave it unchanged)", class: "usa-label" %>
      <%= f.password_field :password_confirmation, class: "usa-input usa-input--xl", autocomplete: "new-password" %>

      <%= f.label :role, class: "usa-label" %>
      <%= f.collection_select :role, Diver::ROLES, :to_s, :humanize, { include_blank: false }, class: "usa-select usa-input--md", autocomplete: "off" %>

      <%= f.submit class: "usa-button" %>
      <%= link_to "Cancel", divers_path, class: "usa-button usa-button--outline" %>
    </div>
  </div>
<% end %>

app/views/divers/edit.html.erb
<%= render "shared/nav_breadcrumbs", object: [["Divers", divers_path], ["Edit Diver", ""]] %>
<%= render 'form' %>

app/views/divers/index.html.erb
<%= render "shared/nav_breadcrumbs", object: [["Divers", ""]] %>

<div class="grid-row">
  <div class="grid-col-12">
    <ul class="usa-button-group margin-bottom-1">
      <li class="usa-button-group__item">
        <%= link_to new_diver_path, class: "new-diver-button usa-button" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#add") %>
          </svg>
          New Diver
        <%- end %>
      </li>
      <li class="usa-button-group__item">
        <%= link_to divers_path(format: "xlsx", nocache: SecureRandom.alphanumeric), class: "usa-button usa-button--accent-cool" do %>
          <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
            <%= tag.use href: image_path("@uswds/uswds/dist/img/sprite.svg#file_download") %>
          </svg> 
          Download Current Diver List (.xlsx)
        <%- end %>
      </li>
    </ul>

    <table class="width-full display">
      <thead>
        <tr>
          <th scope="col" class="width-10">Diver Number</th>
          <th scope="col" class="width-card">Diver Name</th>
          <th scope="col" class="width-10">Active Diver?</th>
          <th scope="col" class="width-card-lg not-orderable not-searchable"></th>
        </tr>
      </thead>
      <tbody>
        <%- @divers.each do |diver| %>
          <tr>
            <td class="width-10"><%= diver.diver_number %></td>
            <td class="width-card"><%= diver.diver_name %></td>
            <td class="width-10"><%= diver.active %></td>
            <td class="width-card-lg">
              <ul class="usa-button-group float-right">
                <li class="usa-button-group__item">
                  <%= link_to "Edit", edit_diver_path(diver), class: "usa-button usa-button--outline" %>
                </li>
                <li class="usa-button-group__item">
                  <%= link_to "Delete", diver, data: { confirm: "Are you sure?" }, method: "delete", class: "usa-button usa-button--secondary" %>
                </li>
              </ul>
            </td>
          </tr>
        <%- end %>
      </tbody>
    </table>
  </div>
</div>

app/views/divers/new.html.erb
<%= render "shared/nav_breadcrumbs", object: [["Divers", divers_path], ["New Diver", ""]] %>
<%= render 'form' %>