config/routes.rb
EntryApplication::Application.routes.draw do
  devise_for :divers, skip: [:registrations], controllers: {
    omniauth_callbacks: "divers/omniauth_callbacks",
  }
  devise_scope :diver do
    get "signin",                       to: "devise/sessions#new"
    get "signout",                      to: "devise/sessions#destroy"
    get "cancel_diver_registration",    to: "devise/registrations#cancel"
    put "diver_registration",           to: "devise/registrations#update"
    get "edit_diver_registration",      to: "devise/registrations#edit"
  end

  # For testing unhandled exceptions via solid_errors
  get "/crash", to: ->(env) { raise "/crash intentionally generated this error for testing error reporting" }

  # Admin only routes
  authenticate :diver, ->(diver) { diver.admin? } do
    mount SolidErrors::Engine, at: "/errors"

    resources :cleanups, only: [:new, :create]
  end

  resources :agencies, except: [:show]

  resources :animals, except: [:show]

  resources :benthic_covers do
    post :draft, on: :collection
  end

  resources :boat_logs do
    post :draft, on: :collection
  end

  resources :coral_demographics do
    post :draft, on: :collection
  end

  resources :corals, except: [:show]

  resources :cover_cats, except: [:show]

  get "dashboard/show"

  resources :divers, except: [:show]

  resources :habitat_types, except: [:show]

  resources :missions, except: [:show]

  resources :projects, except: [:show]

  resources :regions, except: [:show]

  resources :sample_types, except: [:show]

  resources :samples do
    post :draft, on: :collection
  end

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<div class="grid-row padding-y-05">
  <div class="grid-col-12">
    <%= tag.section id: "photo-carousel", class: "splide", "role": "group", "aria-label": "Photo carousel", data: { splide: {"type": "loop", "autoplay": true, interval: 6000 }.to_json } do %>
      <div class="splide__track">
        <ul class="splide__list">
          <li class="splide__slide">
            <%= image_tag "RobvGoliath.JPG" %>
            <div class="font-body-3xs">Photo Credits: Tara Dolan</div>
          </li>
          <li class="splide__slide">
            <%= image_tag "yellowline.jpg" %>
            <div class="font-body-3xs">Photo Credits: Evan D'Alessandro</div>
          </li>
          <li class="splide__slide">
            <%= image_tag "trio.jpg" %>
            <div class="font-body-3xs">Photo Credits: David Bryan, Evan D'Alessandro, Jiangang Luo</div>
          </li>
          <li class="splide__slide">
            <%= image_tag "rustygoby_3.jpg" %>
            <div class="font-body-3xs">Photo Credits: Natalia Zurcher</div>
          </li>
        </ul>
      </div>
    <%- end %>
  </div>
</div>

<div class="grid-row margin-y-05">
  <div class="grid-col-4 text-center">
    <%= link_to samples_path, class: "samples-link font-body-2xs" do %>
      <%= image_tag "FormButton.jpg", width: "145px", height: "145px" %>
      <div>Fish Samples</div>
    <%- end %>
  </div>
  <div class="grid-col-4 text-center">
    <%= link_to benthic_covers_path, class: "benthic-covers-link font-body-2xs" do %>
      <%= image_tag "FormButton.jpg", width: "145px", height: "145px" %>
      <div>Benthic Assessment Samples</div>
    <%- end %>
  </div>
  <div class="grid-col-4 text-center">
    <%= link_to coral_demographics_path, class: "coral-demographics-link font-body-2xs" do %>
      <%= image_tag "FormButton.jpg", width: "145px", height: "145px" %>
      <div>Coral Demographic Samples</div>
    <%- end %>
  </div>
</div>

<div class="grid-row margin-top-3">
  <%- if current_diver&.admin? || current_diver&.missions_managed&.any?  %>
    <div class="grid-col-1 text-center">
      <%= link_to boat_logs_path, class: "boat-logs-link font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Boat Logs</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to dashboard_show_path, class: "dashboard-link font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Manager Dashboard</div>
      <%- end %>
    </div>
  <%- end %>
  <%- if current_diver&.admin? %>
    <div class="grid-col-1 text-center">
      <%= link_to divers_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Diver List</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to animals_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Species List</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to sample_types_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Sample Types</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to habitat_types_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Habitat Types</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to corals_path, class: "corals-link font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Coral List</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to cover_cats_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Cover Category List</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to regions_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Regions</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to agencies_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Agencies</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to projects_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Projects</div>
      <%- end %>
    </div>
    <div class="grid-col-1 text-center">
      <%= link_to missions_path, class: "font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Missions</div>
      <%- end %>
    </div>
  <%- end %>
</div>

<div class="grid-row margin-top-1">
  <%- if current_diver&.admin? %>
    <div class="grid-col-1 text-center">
      <%= link_to new_cleanup_path, class: "boat-logs-link font-body-2xs" do %>
        <%= image_tag "FormButton.jpg", width: "70px", height: "70x" %>
        <div>Data Cleanup</div>
      <%- end %>
    </div>
  <%- end %>
</div>